/**
 * Created by alexanderbol on 13/04/2017.
 */
export const MAIN_CANVAS_MOUNTED = "MAIN_CANVAS_MOUNTED";
export const NEW_STAGE_CREATED = "NEW_STAGE_CREATED";
export const STAGE_RESIZED = "STAGE_RESIZED";

export const NEW_SHAPE_PASTED = "NEW_SHAPE_PASTED";

export const TOGGLE_UNITS_CLICKED = "TOGGLE_UNITS_CLICKED";
export const TOGGLE_WIDTH_MODE_CLICKED = "TOGGLE_WIDTH_MODE_CLICKED";
export const TOGGLE_DISPLAY_VERTICES_CLICKED = "TOGGLE_DISPLAY_VERTICES_CLICKED";
export const TOGGLE_DISPLAY_LABELS_CLICKED = "TOGGLE_DISPLAY_LABELS_CLICKED";

export const MOUSE_MOVED_ON_STAGE = "MOUSE_MOVED_ON_STAGE";
export const MOUSE_DOWN_ON_STAGE = "MOUSE_DOWN_ON_STAGE";
export const MOUSE_UP_ON_STAGE = "MOUSE_UP_ON_STAGE";
export const MOUSE_WHEEL_MOVE_ON_STAGE = "MOUSE_WHEEL_MOVE_ON_STAGE";

export const MOUSE_ROLL_OVER_SHAPE = "MOUSE_ROLL_OVER_SHAPE";
export const MOUSE_ROLL_OUT_SHAPE = "MOUSE_ROLL_OUT_SHAPE";
export const MOUSE_CLICKED_ON_SHAPE = "MOUSE_CLICKED_ON_SHAPE";

// export const HOME_BUTTON_CLICKED = "HOME_BUTTON_CLICKED";
export const PAN_TO_COORDINATE = "PAN_TO_COORDINATE";
export const PAN_AND_ZOOM_TO_SHAPE = "PAN_AND_ZOOM_TO_SHAPE";

export const LAYER_LIST_PANEL_PRESSED = "LAYER_LIST_PANEL_PRESSED";
export const ADD_LAYER_PRESSED = "ADD_LAYER_PRESSED";
export const TOGGLE_DISPLAY_LAYER_PRESSED = "TOGGLE_DISPLAY_LAYER_PRESSED";
export const TOGGLE_AFFECTED_LAYER_PRESSED="TOGGLE_AFFECTED_LAYER_PRESSED";
export const EDIT_LAYER_NAME_PRESSED = "EDIT_LAYER_NAME_PRESSED";
export const LAYERS_LIST_ARROW_DOWN_PRESSED = "LAYERS_LIST_ARROW_DOWN_PRESSED";
export const LAYERS_LIST_ARROW_UP_PRESSED = "LAYERS_LIST_ARROW_UP_PRESSED";

export const TOGGLE_WATCH_EXPAND_CLICKED = "TOGGLE_WATCH_EXPAND_CLICKED";

export const FILENAME_LIST_SELECTED = "FILENAME_LIST_SELECTED";
export const INPUT_FILE_LOADED = "INPUT_FILE_LOADED";

/** Toolbar buttons **/
export const PAN_BY_DRAG_BUTTON_CLICKED = "PAN_BY_DRAG_BUTTON_CLICKED";
export const MEASURE_POINTS_BUTTON_PRESSED = "MEASURE_POINTS_BUTTON_PRESSED";
export const MEASURE_SHAPES_BUTTON_PRESSED = "MEASURE_SHAPES_BUTTON_PRESSED";